alias: "[P3-Salon] Bouton IKEA Inter Salon (4) — ON/OFF Lumière Salon"
description: >
  Pilotage de input_boolean.inter_lumiere_salon via le bouton IKEA 4 touches Salon.
  Topic MQTT : zigbee2mqtt/Inter Salon (4) (IKEA)/action
  ON -> input_boolean.turn_on | OFF -> input_boolean.turn_off
triggers:
  - trigger: mqtt
    options:
      topic: zigbee2mqtt/Inter Salon (4) (IKEA)/action
conditions: []
actions:
  - choose:
      - alias: "BOUTON ON"
        conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'on' }}"
        sequence:
          - action: input_boolean.turn_on
            target:
              entity_id: input_boolean.inter_lumiere_salon
            data: {}
      - alias: "BOUTON OFF"
        conditions:
          - condition: template
            value_template: "{{ trigger.payload_json.action == 'off' }}"
        sequence:
          - action: input_boolean.turn_off
            target:
              entity_id: input_boolean.inter_lumiere_salon
            data: {}
mode: restart
