id: '1775331623943'
alias: P3_BUREAU_ACTIVATION_ECRAN_SYNCHRO
description: Synchronise l'état de l'écran avec l'activité du PC bureau.
triggers:
- alias: 'DÉCLENCHEMENT : PC BUREAU ALLUMÉ'
  trigger: state
  entity_id: binary_sensor.moniteur_pc
  to: 'on'
  id: pc_on
- alias: 'DÉCLENCHEMENT : PC BUREAU ÉTEINT'
  trigger: state
  entity_id: binary_sensor.moniteur_pc
  to: 'off'
  for: 00:02:00
  id: pc_off
conditions: []
actions:
- alias: 'ACTION : SYNCHRONISATION ALIMENTATION ÉCRAN'
  choose:
  - alias: 'CAS : PC ON -> ALLUMER ÉCRAN'
    conditions:
    - condition: trigger
      id: pc_on
    sequence:
    - action: switch.turn_on
      target:
        entity_id: switch.ecran_p_c_3_play_hue
mode: restart
