id: '1775387618751'
alias: '[P3-SALON] BOUTON IKEA SOMRIG — TOUT MESSAGE = ON/OFF'
description: 'Pilotage simplifié : n''importe quel appui sur le bouton 1 (simple,
  double, long)  allume le salon. N''importe quel appui sur le bouton 2 éteint le
  salon.

  '
triggers:
- alias: 'DÉCLENCHEMENT : BOUTON 1 (CLIC SIMPLE)'
  trigger: mqtt
  topic: zigbee2mqtt2/Inter (SOMRIG)/action
  payload: 1_short_release
  id: bouton_on
- alias: 'DÉCLENCHEMENT : BOUTON 1 (DOUBLE CLIC)'
  trigger: mqtt
  topic: zigbee2mqtt2/Inter (SOMRIG)/action
  payload: 1_double_press
  id: bouton_on
- alias: 'DÉCLENCHEMENT : BOUTON 1 (APPUI LONG)'
  trigger: mqtt
  topic: zigbee2mqtt2/Inter (SOMRIG)/action
  payload: 1_long_press
  id: bouton_on
- alias: 'DÉCLENCHEMENT : BOUTON 2 (CLIC SIMPLE)'
  trigger: mqtt
  topic: zigbee2mqtt2/Inter (SOMRIG)/action
  payload: 2_short_release
  id: bouton_off
- alias: 'DÉCLENCHEMENT : BOUTON 2 (DOUBLE CLIC)'
  trigger: mqtt
  topic: zigbee2mqtt2/Inter (SOMRIG)/action
  payload: 2_double_press
  id: bouton_off
- alias: 'DÉCLENCHEMENT : BOUTON 2 (APPUI LONG)'
  trigger: mqtt
  topic: zigbee2mqtt2/Inter (SOMRIG)/action
  payload: 2_long_press
  id: bouton_off
conditions: []
actions:
- alias: 'ACTION : ALLUMER OU ÉTEINDRE'
  choose:
  - alias: 'CAS : N''IMPORTE QUEL APPUI BOUTON 1 -> ALLUMER'
    conditions:
    - condition: trigger
      id: bouton_on
    sequence:
    - action: light.turn_on
      target:
        entity_id: light.salon
  - alias: 'CAS : N''IMPORTE QUEL APPUI BOUTON 2 -> ÉTEINDRE'
    conditions:
    - condition: trigger
      id: bouton_off
    sequence:
    - action: light.turn_off
      target:
        entity_id: light.salon
mode: restart
