id: '1766779091118'
alias: Alerte Météo France actualisation des "CARTES"
description: "Force la mise à jour des images d'alerte Météo France au démarrage,  aux heures clés, ou toutes les 5 min si elles sont indisponibles.\n"
triggers:
- trigger: homeassistant
  event: start
  id: Start
- trigger: time
  at: 06:32:00
  id: Heure632
- trigger: time
  at: '16:32:00'
  id: Heure1632
- trigger: time_pattern
  minutes: /5
  id: Toutesles5minutes
conditions:
- condition: or
  conditions:
  - condition: trigger
    id:
    - Start
    - Heure632
    - Heure1632
  - alias: Vérif si Today est HS
    condition: and
    conditions:
    - condition: trigger
      id: Toutesles5minutes
    - condition: state
      entity_id: sensor.meteo_france_alertes_image_today
      state: unavailable
  - alias: Vérif si Tomorrow est HS
    condition: and
    conditions:
    - condition: trigger
      id: Toutesles5minutes
    - condition: state
      entity_id: sensor.meteo_france_alertes_image_tomorrow
      state: unavailable
actions:
- alias: Premier essai de mise à jour
  action: homeassistant.update_entity
  target:
    entity_id:
    - sensor.meteo_france_alertes_image_today
    - sensor.meteo_france_alertes_image_tomorrow
- delay: 00:00:05
- alias: Répéter MAJ Today si toujours indisponible
  repeat:
    count: 1
    sequence:
    - if:
      - condition: state
        entity_id: sensor.meteo_france_alertes_image_today
        state: unavailable
      then:
      - action: homeassistant.update_entity
        target:
          entity_id: sensor.meteo_france_alertes_image_today
      - delay: 00:00:05
- alias: Répéter MAJ Tomorrow si toujours indisponible
  repeat:
    count: 1
    sequence:
    - if:
      - condition: state
        entity_id: sensor.meteo_france_alertes_image_tomorrow
        state: unavailable
      then:
      - action: homeassistant.update_entity
        target:
          entity_id: sensor.meteo_france_alertes_image_tomorrow
      - delay: 00:00:05
- alias: Rafraîchir les caméras finales
  action: homeassistant.update_entity
  target:
    entity_id:
    - camera.mf_alerte_today
    - camera.mf_alerte_tomorrow
mode: single