id: '1766779355162'
alias: Mettre à jour le temps du dernier impact de foudre
description: 'Met à jour le temps du dernier impact de foudre lorsque le capteur change.'
triggers:
- entity_id: sensor.maison_lightning_counter
  trigger: state
conditions:
- condition: template
  value_template: '{{ states(''sensor.maison_lightning_counter'') | int > 0 }}'
actions:
- target:
    entity_id: input_datetime.dernier_eclair
  data:
    datetime: '{{ now().isoformat() }}'
  action: input_datetime.set_datetime
mode: single