id: '1766948061120'
alias: 'Gestion PC bureau : Scène de Fin + Notif'
description: "Éteint la prise du PC et notifie, mais laisse la prise ON pour le suivi conso  lorsqu'une veille est détectée.\n"
triggers:
- id: bouton_mqtt
  trigger: mqtt
  topic: zigbee2mqtt/Poussoir (IKEA TRADFRI)/action
- id: extinction_conso
  trigger: numeric_state
  entity_id: sensor.prise_bureau_pc_ikea_power
  below: 80
  for:
    minutes: 2
actions:
- choose:
  - alias: 'ALLUMAGE : Bouton ON ou 21h00'
    conditions:
    - or:
      - condition: template
        value_template: '{{ trigger.id == ''bouton_mqtt'' and trigger.payload_json.action
          == ''on'' }}'
      - condition: trigger
        id: bouton_mqtt
    sequence:
    - action: switch.turn_on
      target:
        entity_id: switch.hue_smart_eco_pc_bureau
    - action: switch.turn_on
      target:
        entity_id: switch.prise_bureau_pc_ikea
  - alias: 'EXTINCTION PRISE PC: Bouton OFF ou Veille (< 80W)'
    conditions:
    - or:
      - condition: template
        value_template: '{{ trigger.id == ''bouton_mqtt'' and trigger.payload_json.action
          == ''off'' }}'
      - condition: trigger
        id: extinction_conso
    sequence:
    - action: switch.turn_off
      target:
        entity_id: switch.hue_smart_eco_pc_bureau
    - action: notify.mobile_app_eric
      data:
        title: Veille détectée
        message: PC Bureau [OFF]
        data:
          icon: mdi:eye-outline
          tag: notif_pc_bureau
mode: parallel