id: '1775244397523'
alias: B - Chauffage Cuisine Vacances
description: 'Allume ou éteint le chauffage selon la température entre 6h00 et 8h30 pendant
  les vacances (Tous les jours). Arrêt forcé à 8h30.

  '
triggers:
- id: demarrage
  trigger: time
  at: 06:00:00
- id: arret_force
  trigger: time
  at: 08:30:00
- trigger: numeric_state
  entity_id: sensor.th_cuisine_temperature
  below: 19.9
- trigger: numeric_state
  entity_id: sensor.th_cuisine_temperature
  above: 20.5
conditions: []
actions:
- choose:
  - alias: 'ARRÊT FORCÉ : Fin de période (8h30)'
    conditions:
    - condition: trigger
      id: arret_force
    sequence:
    - action: climate.set_hvac_mode
      target:
        entity_id: climate.radiateur_cuisine
      data:
        hvac_mode: 'off'
    - action: notify.mobile_app_eric
      data:
        message: /!\ RADIATEUR CUISINE est 'OFF' FORCE (Fin Vacances 8h30) /!\
  - alias: 'DÉMARRAGE : Mode Chauffage'
    conditions:
    - alias: Présence Eric ou Mamour
      condition: or
      conditions:
      - condition: zone
        entity_id: person.mamour
        zone: zone.home
      - condition: zone
        entity_id: person.eric
        zone: zone.home
    - condition: time
      after: 06:00:00
      before: 08:30:00
    - condition: numeric_state
      entity_id: sensor.th_cuisine_temperature
      below: 19.9
    sequence:
    - action: climate.set_hvac_mode
      target:
        entity_id: climate.radiateur_cuisine
      data:
        hvac_mode: heat
    - action: notify.mobile_app_eric
      data:
        message: /!\ Chauffage Cuisine 'ON' /!\
  - alias: 'ARRÊT : Température atteinte'
    conditions:
    - alias: Présence Eric ou Mamour
      condition: or
      conditions:
      - condition: zone
        entity_id: person.mamour
        zone: zone.home
      - condition: zone
        entity_id: person.eric
        zone: zone.home
    - condition: time
      after: 06:00:00
      before: 08:30:00
    - condition: numeric_state
      entity_id: sensor.th_cuisine_temperature
      above: 20.5
    sequence:
    - action: climate.set_hvac_mode
      target:
        entity_id: climate.radiateur_cuisine
      data:
        hvac_mode: 'off'
    - action: notify.mobile_app_eric
      data:
        message: /!\ Chauffage Cuisine 'OFF' /!\
mode: single
