alias: "Gestion TV Chambre : Scène de Fin + Notif"
description: |
  Éteint la lumière TV et notifie lorsqu'une veille est détectée.
triggers:
  - id: bouton_mqtt
    trigger: mqtt
    options:
      topic: zigbee2mqtt/Poussoir TV (IKEA TRADFRI)/action
  - id: extinction_conso
    trigger: numeric_state
    entity_id:
      - sensor.prise_tv_chambre_nous_power
    below: 20
    for:
      minutes: 2
actions:
  - choose:
      - alias: "ALLUMAGE : Bouton ON"
        conditions:
          - or:
              - condition: template
                value_template: >-
                  {{ trigger.id == 'bouton_mqtt' and trigger.payload_json is
                  defined and trigger.payload_json.action == 'on' }}
              - condition: trigger
                id: bouton_mqtt
        sequence:
          - action: light.turn_on
            target:
              entity_id: light.hue_smart_eco_tv_chambre
            data: {}
      - alias: "EXTINCTION TV: Bouton OFF ou Veille (< 20W)"
        conditions:
          - or:
              - condition: template
                value_template: >-
                  {{ trigger.id == 'bouton_mqtt' and trigger.payload_json is
                  defined and trigger.payload_json.action == 'off' }}
              - condition: trigger
                id: extinction_conso
        sequence:
          - action: light.turn_off
            target:
              entity_id: light.hue_smart_eco_tv_chambre
            data: {}
          - action: notify.mobile_app_eric
            data:
              title: Veille détectée
              message: TV Chambre [OFF]
              data:
                icon: mdi:eye-outline
                tag: notif_tv_chambre
mode: parallel
