alias: P3_BUREAU - BOUTON RODRET TOGGLE BLANCHES
description: Alterne l'allumage des 2 lampes blanches via MQTT (Mode Fainéant)
triggers:
  - alias: RÉCEPTION MESSAGE MQTT BOUTON RODRET
    trigger: mqtt
    topic: zigbee2mqtt2/Inter Bureau (RODRET)
actions:
  - alias: DÉCISION SELON LE PAYLOAD MQTT (ON OU OFF)
    choose:
      - alias: BOUTON ON OU OFF PRESSÉ -> LOGIQUE TOGGLE
        conditions:
          - alias: VÉRIFICATION ACTION DANS LE JSON
            condition: template
            value_template: "{{ trigger.payload_json.action in ['on', 'off'] }}"
        sequence:
          - alias: LOGIQUE DE BASCULEMENT (TOGGLE)
            choose:
              - alias: SI LUMIÈRE PRÉSENTE -> EXTINCTION
                conditions:
                  - alias: VÉRIFICATION SI UNE LAMPE EST ON
                    condition: or
                    conditions:
                      - condition: state
                        entity_id: light.hue_white_lamp_bureau_1
                        state: "on"
                      - condition: state
                        entity_id: light.hue_white_lamp_bureau_2
                        state: "on"
                sequence:
                  - alias: EXTINCTION DES 2 LAMPES BLANCHES
                    action: light.turn_off
                    target:
                      entity_id:
                        - light.hue_white_lamp_bureau_1
                        - light.hue_white_lamp_bureau_2
              - alias: SI TOUT EST NOIR -> ALLUMAGE
                conditions:
                  - alias: VÉRIFICATION SI TOUT EST OFF
                    condition: state
                    entity_id: light.hue_white_lamp_bureau_1
                    state: "off"
                  - condition: state
                    entity_id: light.hue_white_lamp_bureau_2
                    state: "off"
                sequence:
                  - alias: ALLUMAGE DES 2 LAMPES BLANCHES
                    action: light.turn_on
                    target:
                      entity_id:
                        - light.hue_white_lamp_bureau_1
                        - light.hue_white_lamp_bureau_2
  - alias: FORÇAGE MISE À JOUR DU SENSOR D'ÉTAT
    action: homeassistant.update_entity
    target:
      entity_id: sensor.bureau_etat
mode: restart
