id: '1775331482668'
alias: P3_BUREAU - WATCHDOG SYNCHRONISATION LAMPES BLANCHES
description: Assure que les deux lampes de bureau (1 et 2) sont synchronisées si
  l'une s'allume
triggers:
- alias: DÉTECTION ALLUMAGE LAMPE BUREAU 1
  trigger: state
  entity_id: light.hue_white_lamp_bureau_1
  to: 'on'
  for: 00:00:05
- alias: DÉTECTION ALLUMAGE LAMPE BUREAU 2
  trigger: state
  entity_id: light.hue_white_lamp_bureau_2
  to: 'on'
  for: 00:00:05
conditions:
- alias: VÉRIFICATION SI UNE DES DEUX LAMPES RESTE ÉTEINTE
  condition: or
  conditions:
  - condition: state
    entity_id: light.hue_white_lamp_bureau_1
    state: 'off'
  - condition: state
    entity_id: light.hue_white_lamp_bureau_2
    state: 'off'
actions:
- alias: FORÇAGE ALLUMAGE DES DEUX LAMPES
  action: light.turn_on
  target:
    entity_id:
    - light.hue_white_lamp_bureau_1
    - light.hue_white_lamp_bureau_2
- alias: MISE À JOUR FORCÉE DE L'ÉTAT DU BUREAU
  action: homeassistant.update_entity
  target:
    entity_id: sensor.bureau_etat
mode: restart
