id: '1766779443735'
alias: Z2M last_seen
description: 'Surveillance des capteurs Zigbee injoignables (plus de 8h ou indisponibles)'
triggers:
- trigger: time
  at: 06:00:00
- trigger: time_pattern
  minutes: /15
conditions:
- condition: template
  value_template: '{{ sensors != '''' and (day | int == 0 or day | int == now().isoweekday())
    }}'
actions:
- action: notify.mobile_app_eric
  data:
    title: ⚠️ Problème capteur Zigbee
    message: 'Des capteurs Zigbee ne répondent plus : {{ sensors }}'
variables:
  day: 0
  hours: 8
  exclude:
    entity_id: []
  sensors: "{% set result = namespace(sensors=[]) %} {% for state in states.sensor\
    \ \n   | rejectattr('attributes.device_class', 'undefined') \n   | selectattr('attributes.device_class',\
    \ '==', 'timestamp') %}\n  {% if 'last_seen' in state.entity_id and state.entity_id\
    \ not in exclude.entity_id %}\n    {% set last_seen = states(state.entity_id)\
    \ %}\n    {% if last_seen == 'unavailable' or last_seen == 'unknown' %}\n    \
    \  {% set result.sensors = result.sensors + [state.name | replace(' last seen',\
    \ '') ~ ' (Indisponible)'] %}\n    {% elif (as_timestamp(now()) - as_timestamp(last_seen))\
    \ > (hours | int * 3600) %}\n      {% set result.sensors = result.sensors + [state.name\
    \ | replace(' last seen', '') ~ ' (' ~ relative_time(strptime(last_seen, '%Y-%m-%dT%H:%M:%S%z'))\
    \ ~ ')'] %}\n    {% endif %}\n  {% endif %}\n{% endfor %} {{ result.sensors |\
    \ join(', ') }}\n"
mode: single