# conso_mini = min du jour
- platform: statistics
  name: "Conso Mini"
  unique_id: conso_mini
  entity_id: sensor.ecojoko_consommation_temps_reel
  state_characteristic: min_value
  max_age:
    hours: 24

# conso_maxi = max du jour  
- platform: statistics
  name: "Conso Maxi"
  unique_id: conso_maxi
  entity_id: sensor.ecojoko_consommation_temps_reel
  state_characteristic: max_value
  max_age:
    hours: 24