id: '1766772576096'
alias: (L) (DEBUG) Notifier les changements de message clim (Mobile)
description: "Surveille et notifie les changements d'état du message personnalisé."
triggers:
- trigger: state
  entity_id: sensor.message_clim_personnalise_7h30_21h00
actions:
- choose:
  - alias: 'Détection : CELLULAR'
    conditions:
    - condition: template
      value_template: '{{ ''CELLULAR'' in trigger.to_state.state }}'
    sequence:
    - action: notify.mobile_app_eric
      data:
        message: '[Présence] Personne n''est à la maison (mode CELLULAR/WIFI_?!)'
  - alias: 'Détection : MAMOUR'
    conditions:
    - condition: template
      value_template: '{{ ''MAMOUR'' in trigger.to_state.state }}'
    sequence:
    - action: notify.mobile_app_eric
      data:
        message: '[Présence] Seul Mamour est à la maison (Wi-Fi)'
  - alias: 'Détection : ERIC'
    conditions:
    - condition: template
      value_template: '{{ ''ERIC'' in trigger.to_state.state }}'
    sequence:
    - action: notify.mobile_app_eric
      data:
        message: '[Présence] Seul Eric est à la maison (Wi-Fi)'
  - alias: 'Détection : LES DEUX'
    conditions:
    - condition: template
      value_template: '{{ ''Clim [2] en [WIFI]'' in trigger.to_state.state }}'
    sequence:
    - action: notify.mobile_app_eric
      data:
        message: '[Présence] Mamour et Eric sont à la maison (Wi-Fi)'
  - alias: 'Détection : UP (Hausse)'
    conditions:
    - condition: template
      value_template: '{{ ''Up >>>'' in trigger.to_state.state }}'
    sequence:
    - variables:
        temp_ext: '{{ trigger.to_state.state.split(''|'')[1].split(''Up >>>'')[1].split(''°'')[0].strip()
          }}'
    - action: notify.mobile_app_eric
      data:
        message: '[Tendance] Température extérieure en hausse : {{ temp_ext }}°'
  - alias: 'Détection : DOWN (Baisse)'
    conditions:
    - condition: template
      value_template: '{{ ''Down <<<'' in trigger.to_state.state }}'
    sequence:
    - variables:
        temp_ext: '{{ trigger.to_state.state.split(''|'')[1].split(''Down <<<'')[1].split(''°'')[0].strip()
          }}'
    - action: notify.mobile_app_eric
      data:
        message: '[Tendance] Température extérieure en baisse : {{ temp_ext }}°'
  - alias: 'Détection : STABLE'
    conditions:
    - condition: template
      value_template: '{{ ''stable'' in trigger.to_state.state }}'
    sequence:
    - variables:
        temp_ext: '{{ trigger.to_state.state.split(''|'')[1].split(''°'')[0].split(''stable'')[1].strip()
          }}'
    - action: notify.mobile_app_eric
      data:
        message: '[Tendance] Température extérieure stable : {{ temp_ext }}°'
  - alias: 'Détection : HEAT'
    conditions:
    - condition: template
      value_template: '{{ ''Heat'' in trigger.to_state.state }}'
    sequence:
    - variables:
        message_part: '{{ trigger.to_state.state.split(''|'')[2] }}'
    - action: notify.mobile_app_eric
      data:
        message: '[Mode] Chauffage activé : {{ message_part }}'
  - alias: 'Détection : COOL'
    conditions:
    - condition: template
      value_template: '{{ ''Cool'' in trigger.to_state.state }}'
    sequence:
    - variables:
        message_part: '{{ trigger.to_state.state.split(''|'')[2] }}'
    - action: notify.mobile_app_eric
      data:
        message: '[Mode] Rafraîchissement activé : {{ message_part }}'
  - alias: 'Détection : FAN'
    conditions:
    - condition: template
      value_template: '{{ ''Fan'' in trigger.to_state.state }}'
    sequence:
    - action: notify.mobile_app_eric
      data:
        message: '[Mode] Ventilation activée'