id: '1775244989013'
alias: Gestion Simple du Store Salon (Matin/Soir)
description: Ouvre le store au lever du soleil (pas avant 6h30) et le ferme au coucher.
triggers:
- id: ouverture
  trigger: time
  at: 06:30:00
- id: ouverture
  trigger: sun
  event: sunrise
- id: fermeture
  trigger: sun
  event: sunset
conditions:
- alias: 'SÉCURITÉ : La fenêtre doit être FERMÉE'
  condition: state
  entity_id: binary_sensor.contact_fenetre_salon_sonoff_contact
  state: 'off'
actions:
- choose:
  - alias: 'Matin : Ouverture si > 6h30 ET Soleil levé'
    conditions:
    - condition: trigger
      id: ouverture
    - condition: time
      after: 06:29:00
    - condition: state
      entity_id: sun.sun
      state: above_horizon
    sequence:
    - action: cover.open_cover
      target:
        entity_id: cover.store_salon
  - alias: 'Soir : Fermeture au coucher du soleil'
    conditions:
    - condition: trigger
      id: fermeture
    sequence:
    - action: cover.close_cover
      target:
        entity_id: cover.store_salon
mode: single
